spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev    #开发环境
  application:
    name: springcloud-cofig-shi-dev



---
spring:
  profiles: test   #测试环境
  application:
    name: springcloud-config-shi.dev

#请一定要保存成utf-8的格式

